export const userTypes = {
    SIGN_IN_SUCCESS:'SIGN_IN_SUCCESS',
    SIGN_OUT:'SIGN_OUT'
    

};

export const historyTakingQTypes = {
    CREATE_CASE_Q : 'CREATE_CASE_Q',
    SETCOUNT:'SETCOUNT',
    ALLHISTORYTAKINGQ:'ALLHISTORYTAKINGQ',
    SECTIONORDER: 'SECTIONORDER'
};

export const DentalSheetTypes ={
    CARIES :'CARIES',
    RESTORATION :'RESTORATION'
}
export const caseTypes ={
    SETCASE :'SETCASE',
    SETALLCASES :'SETALLCASES'
}

export const diagnosisTypes ={
    SETDIAGNOSISQ:'SETDIAGNOSISQ',
    SELECTEDANSFORDQ:'SELECTEDANSFORDQ',
    SETCORRECTDIAGNOSISQ:'SETCORRECTDIAGNOSISQ',
    SETWRONGDIAGNOSISQ:'SETWRONGDIAGNOSISQ',
    ISSUBMITDIAGNOSIS:'ISSUBMITDIAGNOSIS'
}
